[package]
name = "axum_typed_multipart"
description = "Type safe multipart/form-data handling for axum."
license = "MIT"
repository = "https://github.com/murar8/axum_typed_multipart"
authors = ["Lorenzo Murarotto <lnzmrr@gmail.com>"]
edition = "2021"
version = "0.1.0"

[workspace]
members = ["core", "macros"]

[dependencies]
axum_typed_multipart_core = { path = "core" }
axum_typed_multipart_macros = { path = "macros" }

[dev-dependencies]
axum = { version = "0.6", features = ["multipart"] }
common-multipart-rfc7578 = "0.6"
futures-util = "0.3"
mime = "0.3"
tempfile = "3.4"
tokio = { version = "1.25", features = ["macros"] }
