[package]
name = "axum_typed_multipart_core"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.6", features = ["multipart"] }

[dev-dependencies]
axum_typed_multipart = { path = "../" }
