[package]
name = "axum_typed_multipart_macros"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc_macro = true

[dependencies]
darling = "0.14"
proc-macro-error = "1.0"
quote = "1.0"
syn = "1.0"
