on:
  pull_request: { branches: [main] }
  push: { tags: ["[0-9]+.[0-9]+.[0-9]+"] }

env:
  RUSTFLAGS: -Dwarnings # Make sure CI fails on all warnings.

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.1.0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-features --all-targets --no-deps

      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --all-features

  test:
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features --all-targets

  publish:
    if: startsWith(github.event.ref, 'refs/tags/')

    needs:
      - lint
      - test

    env:
      CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --locked --package axum_typed_multipart_macros

      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --locked
