on:
  pull_request: { branches: ["main"] }
  push: { branches: ["main"] }

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with: { toolchain: "stable" }

      - name: Restore Cargo Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-features --no-deps

      - name: Check Docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --all-features

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features --all-targets

      - name: Publish Macros
        if: github.event_name != 'pull_request'
        uses: actions-rs/cargo@v1
        env: { CARGO_REGISTRY_TOKEN: "${{secrets.CARGO_REGISTRY_TOKEN}}" }
        with:
          command: publish
          args: --package axum_typed_multipart_macros

      - name: Publish Core
        if: github.event_name != 'pull_request'
        uses: actions-rs/cargo@v1
        env: { CARGO_REGISTRY_TOKEN: "${{secrets.CARGO_REGISTRY_TOKEN}}" }
        with:
          command: publish
