on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: dependabot/fetch-metadata@v1
        id: metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: gh pr merge --auto --rebase ${{github.event.pull_request.html_url}}
        if: ${{ github.actor == 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
