on:
  pull_request:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: dependabot/fetch-metadata@v1
        id: metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: gh pr merge --auto --rebase ${{github.event.pull_request.html_url}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
