on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  auto-merge:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' }}

    needs:
      - lint
      - test

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: dependabot/fetch-metadata@v1
        id: metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          gh pr review --approve ${{github.event.pull_request.html_url}}
          gh pr merge --auto --rebase ${{github.event.pull_request.html_url}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
